# Enhanced Keywords Template - This is what the external ChatGPT should generate
# Replace the simple keywords.py with this enhanced structure

keywords = {
    "Café da manhã sem culpa": {
        "primary_keywords": ["café da manhã saudável", "café da manhã saudável para emagrecer"],
        "long_tail_keywords": ["receitas de café da manhã saudável", "cardápio café da manhã saudável"],
        "related_searches": ["café da manhã saudável simples", "café da manhã rápido"],
        "search_volume": {
            "café da manhã saudável": 1200,
            "café da manhã saudável para emagrecer": 800,
            "receitas de café da manhã saudável": 600
        },
        "competition_level": "medium",
        "search_intent": "informational",
        "h1": "Tudo sobre café da manhã saudável para emagrecer",
        "h2": ["O que é café da manhã saudável?", "Como preparar café da manhã saudável", "Benefícios do café da manhã saudável"],
        "suggested_titles": ["Guia completo: Café da manhã saudável para emagrecer", "5 receitas de café da manhã saudável"]
    },
    "Snacks on-the-go": {
        "primary_keywords": ["snacks saudáveis", "lanche prático saudável"],
        "long_tail_keywords": ["snacks saudáveis para viagem", "lanche rápido nutritivo"],
        "related_searches": ["snacks naturais", "snacks sem ultraprocessados"],
        "search_volume": {
            "snacks saudáveis": 1800,
            "lanche prático saudável": 900,
            "snacks saudáveis para viagem": 500
        },
        "competition_level": "low",
        "search_intent": "commercial",
        "h1": "Snacks saudáveis para sua rotina diária",
        "h2": ["O que são snacks saudáveis?", "Como escolher snacks práticos", "Benefícios dos snacks naturais"],
        "suggested_titles": ["Snacks saudáveis: Guia completo para sua rotina", "10 snacks práticos para viagem"]
    },
    "Latte art Barista": {
        "primary_keywords": ["leite vegetal barista", "latte art com leite de aveia"],
        "long_tail_keywords": ["como fazer latte art", "café com leite vegetal"],
        "related_searches": ["leite de aveia para café", "bebida vegetal barista"],
        "search_volume": {
            "leite vegetal barista": 400,
            "latte art com leite de aveia": 200,
            "como fazer latte art": 1500
        },
        "competition_level": "high",
        "search_intent": "informational",
        "h1": "Latte art com leite vegetal: Guia completo",
        "h2": ["O que é latte art?", "Como usar leite vegetal", "Técnicas de barista"],
        "suggested_titles": ["Latte art com leite vegetal: Técnicas de barista", "Guia completo para latte art"]
    },
    "Lanches saudáveis": {
        "primary_keywords": ["lanche saudável", "lanche fitness"],
        "long_tail_keywords": ["lanche saudável rápido", "lanche saudável para tarde"],
        "related_searches": ["lanche nutritivo", "lanches práticos sem ultraprocessados"],
        "search_volume": {
            "lanche saudável": 2200,
            "lanche fitness": 1100,
            "lanche saudável rápido": 700
        },
        "competition_level": "medium",
        "search_intent": "commercial",
        "h1": "Lanches saudáveis para sua rotina fitness",
        "h2": ["O que é um lanche saudável?", "Como preparar lanches rápidos", "Benefícios dos lanches nutritivos"],
        "suggested_titles": ["Lanches saudáveis: 15 opções para sua rotina", "Guia rápido de lanches fitness"]
    },
    "Sustentabilidade Nude": {
        "primary_keywords": ["bebidas vegetais", "alternativa ao leite tradicional"],
        "long_tail_keywords": ["sustentabilidade alimentação", "impacto ambiental leite vegetal"],
        "related_searches": ["benefícios das bebidas vegetais", "alimentação sustentável"],
        "search_volume": {
            "bebidas vegetais": 1600,
            "alternativa ao leite tradicional": 800,
            "sustentabilidade alimentação": 1200
        },
        "competition_level": "low",
        "search_intent": "informational",
        "h1": "Sustentabilidade na alimentação: Bebidas vegetais",
        "h2": ["O que são bebidas vegetais?", "Impacto ambiental", "Benefícios sustentáveis"],
        "suggested_titles": ["Sustentabilidade na alimentação: Guia completo", "Bebidas vegetais e meio ambiente"]
    }
}

# This enhanced structure provides:
# - Primary and long-tail keywords with search volume data
# - Related searches for content expansion
# - Competition level analysis
# - Search intent classification
# - Pre-optimized H1 and H2 headers
# - Suggested titles for content
# - All the data previously generated by extract_seo
