# Learn more about configuring your app at https://shopify.dev/docs/apps/tools/cli/configuration

client_id = "4dec87e5cdcb6461e168baa7efe72f24"
name = "nami"
application_url = "https://villas-ones-rouge-app.trycloudflare.com"
embedded = true
handle = "nami-1"

[build]
include_config_on_deploy = true
automatically_update_urls_on_dev = true

[webhooks]
api_version = "2025-07"

  [[webhooks.subscriptions]]
  topics = [ "app/uninstalled" ]
  uri = "/webhooks/app/uninstalled"

  [[webhooks.subscriptions]]
  topics = [ "app/scopes_update" ]
  uri = "/webhooks/app/scopes_update"

[access_scopes]
# Learn more at https://shopify.dev/docs/apps/tools/cli/configuration#access_scopes
scopes = "write_products"

[auth]
redirect_urls = ["https://villas-ones-rouge-app.trycloudflare.com/auth/callback", "https://villas-ones-rouge-app.trycloudflare.com/auth/shopify/callback", "https://villas-ones-rouge-app.trycloudflare.com/api/auth/callback"]

[pos]
embedded = false
