[project]
name = "controller"
version = "0.1.0"
description = "controller using crewAI"
authors = [{ name = "Your Name", email = "you@example.com" }]
requires-python = ">=3.10,<3.13"
dependencies = [
    "crewai[tools]>=0.108.0,<1.0.0"
]

[project.scripts]
controller = "controller.main:run"
run_crew = "controller.main:run"
train = "controller.main:train"
replay = "controller.main:replay"
test = "controller.main:test"

[build-system]
requires = ["hatchling"]
build-backend = "hatchling.build"

[tool.crewai]
type = "crew"
entrypoint = "controller/src/controller/main.py"
