[project]
name = "insighter"
version = "0.1.0"
description = "insighter using crewAI"
authors = [{ name = "Your Name", email = "you@example.com" }]
requires-python = ">=3.10,<3.14"
dependencies = [
    "crewai[tools]>=0.130.0,<1.0.0"
]

[project.scripts]
insighter = "insighter.main:run"
run_crew = "insighter.main:run"
train = "insighter.main:train"
replay = "insighter.main:replay"
test = "insighter.main:test"

[build-system]
requires = ["hatchling"]
build-backend = "hatchling.build"

[tool.crewai]
type = "crew"
